import {Model} from 'sequelize';
import { Json } from 'sequelize/types/lib/utils';

export class User extends Model{
    pk!: number;
    username!: string;
    fullName!: string;
    isPrivate!: boolean;
    profilePicUrl!: string;
    profilePicId!: string;
    isVerified!: boolean;
    hasAnonymousProfilePicture!: boolean;
    mediaCount!: number;
    geoMediaCount!: number;
    followerCount!: number;
    followingCount!: number;
    followingTagCount!: number;
    biography!: string;
    externalUrl!: string;
    totalIgtvVideos!: number;
    totalArEffects!: number;
    reelAutoArchive!: string;
    usertagsCount!: number;
    isFavorite!: boolean;
    isInterestAccount!: boolean;
    hasChaining!: boolean;
    hdProfilePicVersions!: any;
    hdProfilePicUrlInfo!: any;
    mutualFollowersCount!: number;
    profileContext!: string;
    profileContextLinksWithUserIds!: any;
    profileContextMutualFollowIds!: any;
    hasHighlightReels!: boolean;
    canBeReportedAsFraud!: boolean;
    isBusiness!: boolean;
    isCallToActionEnabled!: boolean;
    accountType!: number;
    includeDirectBlacklistStatus!: string;
    isPotentialBusiness!: boolean;
    isBestie!: boolean;
    hasUnseenBestiesMedia!: boolean;
    showAccountTransparencyDetails!: string;
    autoExpandChaining!: string;
    highlightReshareDisabled!: string;
    picture!: string;
    id!: number;
}